### ISSUE TITLE
Repeatedly prompted to enter login credentials

### ISSUE THREAD

**Issue by scottgolightly** [rappen/PluginTraceViewer#169]
For about 24 hours I have been prompted repeatedly to log in to the environment. I am using the same credentials as I used to establish the connection. After several prompts I get a message that I could not log in and then the prompts start all over again. I eventually got this error. So far Plugin Trace Viewer is the only tool that is prompting me to log in again when I use it. If I am quick and close the login prompt, click the refresh button I can see the updated plugin logs so I am connected and it is working.
I haven't tried this with other environments to see if this is environment specific.
I have tried logging out and logging back in, closing XRM Toolbox and ensuring that it isn't still running, and rebooting to see if any of those would fix the issue.

---
```
System.AggregateException:
One or more errors occurred.
mscorlib
- Microsoft.Xrm.Tooling.Connector.CrmServiceClient.RetrieveMultiple(QueryBase query)
- Cinteros.XTB.PluginTraceViewer.PluginTraceViewer.<>c__DisplayClass50_0.<RefreshTraces>b__0(BackgroundWorker a, DoWorkEventArgs args)
- System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
- System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

---
- XrmToolBox Version: 1.2022.4.55
- Plugin Trace Viewer Version: 1.2022.2.2
- DB Version: 9.2.22033.156
- Deployment: Online

**Comment by rappen** [comment]
I have seen the same thing... 😔
I have no idea right now - but I will investigate, and I would love any help you find out!
Maybe @MscrmTools might have anything?

**Comment by rappen** [comment]
I assume this issue is solved på XrmToolBox.
Please reopen it if needed!
