### ISSUE TITLE
Extra filtering conditions

### ISSUE THREAD

**Issue by eleung83** [rappen/PluginTraceViewer#179]
This would be more of a nice to have and it could easily just be done by exporting to Excel, but would it be possible to add extra filters, e.g exclude Message types (Create/Update/delete etc) and exclude Plugins

**Comment by rappen** [comment]
Thanks for your ideas!

However, I don't really understand what you are missing...
We can filter like this:

![image](https://github.com/rappen/PluginTraceViewer/assets/2572253/8a026d05-55ef-496d-ac41-fd4f4ffa30a1)

Now I'm excluded plugins from Microsoft and ClickDimention with the plugin filter: `!Microsoft*, !clickdimensions*`
Now only showing messages: `Delete, Create`

What more do you need? 😊

**Comment by eleung83** [comment]
Ah, I wasn't aware of the "!" operator being available. Is it available for all of the filter options, e.g. if, within one correlation ID, I wanted to ignore "RetrieveMultiple" message, but include "Create" message

**Comment by rappen** [comment]
Try it! I don't really remember... 😂

Not that you can also add more than one, like `Create, Update, Delete`.
And you can combine like `*log*, !Microsoft`

**Comment by eleung83** [comment]
ok, I'll close this for now till I get another chance to apply similar filters again
