### ISSUE TITLE
XrmToolBox.PluginsStore, Version=1.2022.2.54

### ISSUE THREAD

**Issue by uippnortejoa** [rappen/PluginTraceViewer#182]
I guess the plugin has stop working on last XrmToolbox update.
Could not load file or assembly 'XrmToolBox.PluginsStore, Version=1.2022.2.54, Culture=neutral, PublicKeyToken=null'

Any idea's about how we can solve this?
Thanks.

**Comment by rappen** [comment]
Hi, an interim solution is found here: https://jonasr.app/missing-xrmtoolbox-pluginsstore/
I will release a new version of Plugin Trace Viewer as soon as I can.
Stay tuned...
