### ISSUE TITLE
Open external text editor for log files

### ISSUE THREAD

**Issue by shytikov** [rappen/PluginTraceViewer#19]
I think every developer has their own preference in text editors. So it would be nice to open log entry in that editor when we're double-clicking on log entry.

**Comment by rappen** [comment]
How should "your preferred editor" be specified?

**Comment by shytikov** [comment]
I think it should be setting somewhere in the plugin, but if it's missing we can start standard system text editor, which is registered for `.txt` extension.

**Comment by rappen** [comment]
Available like this from next release:

![image](https://user-images.githubusercontent.com/2572253/70265982-ddfdf800-179b-11ea-946c-ece03a26df69.png)
