### ISSUE TITLE
Sorting by duration doesn't function properly

### ISSUE THREAD

**Issue by seanmcne** [rappen/PluginTraceViewer#53]
![image](https://cloud.githubusercontent.com/assets/2292260/25561282/85a8bc76-2d2e-11e7-80f9-f9a8e7d3148d.png)

**Comment by rappen** [comment]
Aargh, it sorts them as text... 🤕

**Comment by seanmcne** [comment]
Yeah - bummer :(  

The datagrid must not understand that the column data type is a double or int.

**Comment by rappen** [comment]
Fixed by https://github.com/Innofactor/CRMWinForm/commit/f973d4a7900bf8b6e1b8107bb72c26943108625f
Available from next released PTV.

**Comment by seanmcne** [comment]
@rappen Jonas is it possible this regressed?  I just noticed it isn't sorting correctly again. 
![image](https://github.com/rappen/PluginTraceViewer/assets/2292260/0340e915-e11b-4d46-9095-d3642a4046f3)
![image](https://github.com/rappen/PluginTraceViewer/assets/2292260/f33e1d57-4596-464e-9ed6-7c5cb06b2576)
