### ISSUE TITLE
Allow to filter list based on trace content search

### ISSUE THREAD

**Issue by MscrmTools** [rappen/PluginTraceViewer#73]
It would be awesome to add a filter textbox so that you can filter trace listed only if the trace message contains the term searched.

**Comment by rappen** [comment]
![image](https://user-images.githubusercontent.com/2572253/45212402-18c16980-b295-11e8-8859-6b68fb80dafa.png)

**Comment by MscrmTools** [comment]
Hidden gem! Thanks
