### ISSUE TITLE
Prompt users to set Trace Log Settings to Off when they close the Plugin Trace Viewer

### ISSUE THREAD

**Issue by JimDaly** [rappen/PluginTraceViewer#74]
Microsoft recommends that the `Organization.PluginTraceLogSetting` value is set to **Off** (or at least **Exception**) unless people are actively using tracing to debug.

It is easy to forget to change this back when you are done. Leaving this set to **All** in particular can help fill up the DB tables and lead to decreased performance.

To help remind people of this best practice when using the PTV, I think it would be great if there was a prompt when closing to provide an opportunity for them to set the value to **Exception** or **Off**.

**Comment by rappen** [comment]
WIll this do?

![image](https://user-images.githubusercontent.com/2572253/44684363-33037800-aa49-11e8-99ae-1c99802120ce.png)

Shown when closing PTV and current setting is 'All'.
No message if setting is 'Exception' or 'None'.
If user wants to change to 'Exception' just click Cancel and change manually.

**Comment by JimDaly** [comment]
Nice!
