### ISSUE TITLE
Links in Trace Message view

### ISSUE THREAD

**Issue by aslanovsergey** [rappen/PluginTraceViewer#76]
It it possible to make links to open in browser?

![image](https://user-images.githubusercontent.com/22150933/46800394-32584400-cd60-11e8-966e-588bc0ce2baf.png)

**Comment by rappen** [comment]
Never tried that!
They look "blue and clickable", but I guess nothing happens when you click?

**Comment by aslanovsergey** [comment]
Yes, but would be very useful to open records when debugging.

**Comment by rappen** [comment]
Not sure I am following you... From your reply I guess clicking the links work, how do you mean "when debugging"?

**Comment by rappen** [comment]
Any more info to this @aslanovsergey since I'm working on a new release?
