### ISSUE TITLE
Selecting one single line clears whole window 🤪💣👿👌

### ISSUE THREAD

**Issue by shytikov** [rappen/PluginTraceViewer#77]
Have found strangest bug ever!

If try to select one single line using cutter on the left side of the list interface will go gray and that's it. Plugin restart would be needed to fix that. Using version 1.2018.9.2.

Here comes screenshots:

![image](https://user-images.githubusercontent.com/1185905/47799325-5210d580-dd2a-11e8-8b1f-67622d11e238.png)

Here how it will look after the click on any of squares in red:

![image](https://user-images.githubusercontent.com/1185905/47799357-61901e80-dd2a-11e8-9ff7-2a0a16b71f7f.png)

But if you will make windows wide enough you would be able to see some logs on far-far right:

![image](https://user-images.githubusercontent.com/1185905/47799369-6b198680-dd2a-11e8-8501-04ebd2f39d6a.png)

**Comment by rappen** [comment]
That looks very unpleasant...!
Looked in the code to get any clue? 😉

**Comment by shytikov** [comment]
Not yet... Will try to search for the reason now...

**Comment by rappen** [comment]
Any update?
