### ISSUE TITLE
Scroll Bars are too Scrolly

### ISSUE THREAD

**Issue by daryllabar** [rappen/PluginTraceViewer#78]
https://www.screencast.com/t/unddiQfAv

When clicking in the text box, it scrolls to the top...

**Comment by rappen** [comment]
Simple explanation: When the content is changed (selecting a new row) the cursor position is set to 0;0. When the textbox gets focus, the control makes sure the cursor position is visible.

Solution 1: Make sure textbox is always scrolled to top when selecting new row. Downside: trying to compare content "far down" of different log records gets hard.
Solution 2: Try to place cursor at top;left position in currently visible text based on current scroll-state. Downside: how to implement?

**Comment by rappen** [comment]
Pull Requests welcome!! 😁

**Comment by daryllabar** [comment]
Raise the Bar episode 9?

**Comment by rappen** [comment]
Hit it! 💪

**Comment by rappen** [comment]
I guess this never made it to Raise the Bar... 😉
