### ISSUE TITLE
Pipe character in connection name leads to path error

### ISSUE THREAD

**Issue by ccellar** [rappen/PluginTraceViewer#82]
When the connection name includes a pipe `|` character (like `CUSTOMER | DEV`), the plugin won`t load because it tries to load the settings file in a path which is built in combination with the connection name:
https://github.com/rappen/PluginTraceViewer/blob/master/PluginTraceViewer/PluginTraceViewer.cs#L258

Exception is: 

> An error occured when trying to display this plugin: Illegal character in path.

**Comment by rappen** [comment]
Same as https://github.com/rappen/FetchXMLBuilder/issues/269
Will be fixed in XrmToolBox main repository.
