### ISSUE TITLE
Exceptions with New Lines Breaks Matching

### ISSUE THREAD

**Issue by daryllabar** [rappen/PluginTraceViewer#86]
![image](https://user-images.githubusercontent.com/9728423/67892894-0014b280-fb2c-11e9-9992-3e8eb6093f49.png)

When I click on the Exception cell, the status bar thing at the bottom goes crazy.  I believe it's due to new lines in the Exception not getting stripped on the Match Logic.

**Comment by rappen** [comment]
Ugly, gah, thanks. Will fix.
